project_id = "zxuyvgmouylbibyrkizy"

[functions.vultr-inference]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-voices]
verify_jwt = false

[functions.fashion-assistant]
verify_jwt = false

[functions.style-recommendations]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false
